### ISSUE TITLE
Problem with attribute selection rules of aux_cols for linkability evaluation

### ISSUE THREAD

**Issue by Lz73573** [statice/anonymeter#22]
For personal data sets, how should attributes be selected from the auxiliary attribute sets aux_cols[0] and aux_cols[1] in linkability evaluation?

**Comment by MatteoGiomi** [comment]
Hi, 

In the `LinkabilityEvaluator` there is no selection of the attributes from `aux_cols[0]` and `aux_cols[1]`, as all the attributes in these two lists are used (see [here](https://github.com/statice/anonymeter/blob/main/src/anonymeter/evaluators/linkability_evaluator.py#L135-L136)). Using the same language as the paper, `aux_cols[0]` are the columns in the external dataset A, and `aux_cols[1]` are the columns in eternal dataset B.

**Comment by Lz73573** [comment]
Sorry, let me describe my problem again. In the code, the total number of attributes for the given dataset is 15, but the selection of auxiliary attributes in the Linkability evaluation is 10 of them to construct auxiliary columns:

Aux_ Cols=[

['type employee ',' education ',' hr_per_week ',' capital loss', 'capital gain'],

['race', 'sex', 'fnlwgt', 'age', 'country']

]

I would like to ask what rules are followed for the selection of these 10 attributes, so that I can apply the same rules to the selection of our dataset

**Comment by MatteoGiomi** [comment]
Using different `aux_cols` you can "model" different attackers. For this there is no fixed general rule, since there can be many different attack scenario that you might want to consider. 

The choice I made in the notebook that you are referring to is rather arbitrary, feel free to change these values and see if/how the risk changes. A good (although compute intensive) approach to evaluate the overall risk is to run the evaluation multiple times, each time with a random selection of auxiliary columns.

**Comment by eicca** [comment]
Closing this, as the question was answered.
