### ISSUE TITLE
Sanity Check fails in cases of low attack success

### ISSUE THREAD

**Issue by tiadams** [statice/anonymeter#33]
We are currently testing your framework on several differential private (DP) synthetic datasets and have come to notice that in many cases the sanity check (random guessing) fails for both the single- and multivariate singling-out attack. This is not due to the sanity check being particularity successful (success rate lower than 0.5%), but due to the actual attacks also being similarly unsuccessful as the sanity check.

Imo for this case the attacks should not be considered as failed due to the fact that there simply is no knowledge to infer based on the synthetic data due to DP guarantees. 

What is your view on this?

**Comment by MatteoGiomi** [comment]
Hi @tiadams, 

thanks for the question. The purpose of the sanity check is to avoid to underestimate the risk simply because the user has modeled a weak attacker. 

As you correctly point out, the strength of the attacker depends on the amount of (private) information about target records that is present in the synthetic data. If the synthetic data contains little or no information on the targets, the attacker should not be able to do better than guessing at random.

However, since these success rates are estimated in a statistical fashion, you also have to consider the statistical errors on your measures. Even with DP, some small amount of private information will be leaked, and it could become measurable with enough statistic. So, if you have a lot of time and a big computer, you could run many more attacks (larger `n_attacks`) and try to reduce the error bars. 

More concretely, I think that you have to decide, based on what you want to do eventually, whether to consider the attack as failed, and thus maybe to overestimate the risk, or to consider the risk compatible with 0 for these cases. I took the first approach to be more conservative by default, but there could be cases in which the second is more reasonable.

**Comment by MatteoGiomi** [comment]
I'm closing this. Feel free to re-open it.
